export const eventList = [
  {
    id: 1,
    name: 'Euro 2020',
    startDate: new Date('2020-06-12'),
    endDate: new Date('2020-07-12'),
    description:
      'Et harum quidem rerum facilis est et expedita distinctio. Aenean placerat. Aenean fermentum risus id tortor. Donec quis nibh at felis congue commodo. Nullam dapibus fermentum ipsum. Morbi leo m.',
  },
  {
    id: 2,
    name: 'Euro 2024',
    startDate: new Date('2024-06-12'),
    endDate: new Date('2024-07-12'),
    description:
      'Et harum quidem rerum facilis est et expedita distinctio. Aenean placerat. Aenean fermentum risus id tortor. Donec quis nibh at felis congue commodo. Nullam dapibus fermentum ipsum. Morbi leo m.',
  },
  {
    id: 3,
    name: 'Euro 2028',
    startDate: new Date('2028-06-12'),
    endDate: new Date('2028-07-12'),
    description:
      'Et harum quidem rerum facilis est et expedita distinctio. Aenean placerat. Aenean fermentum risus id tortor. Donec quis nibh at felis congue commodo. Nullam dapibus fermentum ipsum. Morbi leo m.',
  },
  {
    id: 4,
    name: 'Euro 2032',
    startDate: new Date('2032-06-12'),
    endDate: new Date('2032-07-12'),
    description:
      'Et harum quidem rerum facilis est et expedita distinctio. Aenean placerat. Aenean fermentum risus id tortor. Donec quis nibh at felis congue commodo. Nullam dapibus fermentum ipsum. Morbi leo m.',
  },
  {
    id: 5,
    name: 'Euro 2036',
    startDate: new Date('2036-06-12'),
    endDate: new Date('2036-07-12'),
    description:
      'Et harum quidem rerum facilis est et expedita distinctio. Aenean placerat. Aenean fermentum risus id tortor. Donec quis nibh at felis congue commodo. Nullam dapibus fermentum ipsum. Morbi leo m.',
  },
];

export const lobbyList = [
  {
    id: 1,
    name: 'Grupa 1',
    joinedUsers: 3,
    minimumUsers: 4,
    maxUsers: 7,
    eventName: 'Euro 2020',
  },
  {
    id: 2,
    name: 'Grupa 2',
    joinedUsers: 1,
    maxUsers: 9,
    minimumUsers: 4,
    eventName: 'Euro 2020',
  },
  {
    id: 3,
    name: 'Grupa 3',
    minimumUsers: 4,
    joinedUsers: 7,
    maxUsers: 8,
    eventName: 'Euro 2020',
  },

  {
    id: 4,
    name: 'Full mocked group',
    minimumUsers: 4,
    joinedUsers: 7,
    maxUsers: 7,
    eventName: 'Euro 2020',
  },
];

export const gamerList = [
  {
    lobbyId: 1,
    name: 'Adam',
    playerListId: 1,
  },
  {
    lobbyId: 1,
    name: 'Kotlik',
    playerListId: 2,
  },
  {
    lobbyId: 1,
    name: 'Morava',
    playerListId: 3,
  },
];

export const playerList = [
  {
    id: 43,
    name: 'Aleš Hruška',
    position: 'B',
    team: 'FC VIKTORIA PLZEŇ',
    earnings: 120,
    earningsPercentage: '3%',
    profitLoss: 120,
    playerListId: 1,
  },
  {
    id: 6,
    name: 'Jan Bořil',
    position: 'O',
    team: 'SK SLAVIA PRAHA',
    earnings: 240,
    earningsPercentage: '7%',
    profitLoss: 0,
    playerListId: 1,
  },
  {
    id: 53,
    name: 'Roman Hubník',
    position: 'O',
    team: 'FC VIKTORIA PLZEŇ',
    earnings: 0,
    earningsPercentage: '0%',
    profitLoss: 0,
    playerListId: 1,
  },
  {
    id: 128,
    name: 'Břečka Tomáš',
    position: 'O',
    team: 'FK JABLONEC',
    earnings: 150,
    earningsPercentage: '4%',
    profitLoss: 0,
    playerListId: 1,
  },
  {
    id: 25,
    name: 'Petr Ševčík',
    position: 'Z',
    team: 'SK SLAVIA PRAHA',
    earnings: 450,
    earningsPercentage: '13%',
    profitLoss: 0,
    playerListId: 1,
  },
  {
    id: 144,
    name: 'Jan Sýkora',
    position: 'Z',
    team: 'FK JABLONEC',
    earnings: 720,
    earningsPercentage: '21%',
    profitLoss: 0,
    playerListId: 1,
  },
  {
    id: 219,
    name: 'Radim Breite',
    position: 'Z',
    team: 'FC SLOVAN LIBEREC',
    earnings: 60,
    earningsPercentage: '2%',
    profitLoss: 30,
    playerListId: 1,
  },
  {
    id: 466,
    name: 'Petržela Milan',
    position: 'Z',
    team: '1.FC SLOVÁCKO',
    earnings: 270,
    earningsPercentage: '8%',
    profitLoss: 120,
    playerListId: 1,
  },
  {
    id: 75,
    name: 'Michael Krmenčík',
    position: 'U',
    team: 'FC VIKTORIA PLZEŇ',
    earnings: 360,
    earningsPercentage: '10%',
    profitLoss: 0,
    playerListId: 1,
  },
  {
    id: 112,
    name: 'Adam Hložek20',
    position: 'U',
    team: 'AC SPARTA PRAHA',
    earnings: 630,
    earningsPercentage: '18%',
    profitLoss: 0,
    playerListId: 1,
  },
  {
    id: 309,
    name: 'Jakub Yunis',
    position: 'U',
    team: 'SK SIGMA OLOMOUC',
    earnings: 0,
    earningsPercentage: '0%',
    profitLoss: 0,
    playerListId: 1,
  },
  {
    id: 44,
    name: 'Matúš Kozáčik',
    position: 'B',
    team: 'FC VIKTORIA PLZEŇ',
    earnings: 0,
    earningsPercentage: '0%',
    profitLoss: 0,
    playerListId: 1,
  },
  {
    id: 212,
    name: 'Ondřej Karafiát',
    position: 'O',
    team: 'FC SLOVAN LIBEREC',
    earnings: 60,
    earningsPercentage: '2%',
    profitLoss: 30,
    playerListId: 1,
  },
  {
    id: 409,
    name: '5 David Bartek',
    position: 'O',
    team: 'BOHEMIANS 1905',
    earnings: 240,
    earningsPercentage: '7%',
    profitLoss: 30,
    playerListId: 1,
  },
  {
    id: 264,
    name: 'Michal Hubínek',
    position: 'Z',
    team: 'FK MLADÁ BOLESLAV',
    earnings: 90,
    earningsPercentage: '3%',
    profitLoss: 0,
    playerListId: 1,
  },
  {
    id: 188,
    name: 'Milan Baroš',
    position: 'U',
    team: 'FC BANÍK OSTRAVA',
    earnings: 0,
    earningsPercentage: '0%',
    profitLoss: 120,
    playerListId: 1,
  },
  {
    id: 348,
    name: 'PAVEL VYHNAL',
    position: 'U',
    team: 'FASTAV ZLÍN',
    earnings: 0,
    earningsPercentage: '0%',
    profitLoss: 0,
    playerListId: 1,
  },
  {
    id: 350,
    name: 'ANTONÍN FANTIŠ',
    position: 'U',
    team: 'FASTAV ZLÍN',
    earnings: 90,
    earningsPercentage: '3%',
    profitLoss: 0,
    playerListId: 1,
  },
];

export const mocks = {
  eventList,
  lobbyList,
  playerList,
  gamerList,
};
