export default {
  empty: () => '/',
  login: () => '/login',
  registration: () => '/registration',
  activateUser: () => '/activate-user/:userHash',
  getActivateUser: () => '/activate-user',
  resetPassword: () => '/reset-password',
  resetPasswordConfirmation: () => '/reset-password-confirmation/:userHash',
  getResetPasswordConfirmation: () => '/reset-password-confirmation',
  home: () => '/home',
  settings: () => '/settings',
  eventDetail: () => '/event/:eventId',
  lobbyDetail: () => '/lobby/:lobbyId',
  getEventDetail: id => `/event/${id}`,
  getLobbyDetail: id => `/lobby/${id}`,
};
